### ISSUE TITLE
Inquiry about the numbers in Table. 2 for ACDC dataset

### ISSUE THREAD

**Issue by AbdelrahmanShakerYousef** [kkk55596/D-Former#2]
Hello,

I have one inquiry, please. In Table. 2 in D-Former paper, you mentioned that the results of nnFormer on the ACDC dataset are as follows:
**RV**: 90.22, **Myo**: 89.53, **LV**: 95.59, and **Avg-3** is 91.78

However, the results of nnFormer for the ACDC dataset (from nnFromer paper) are as follows:
**RV**: 90.94, **Myo**: 89.58, **LV**: 95.65, and **Avg-3** is 92.06

Could you please clarify that?

**Comment by kkk55596** [comment]
We followed the result of first edition of nnFormer, and they are now in its sixth edition
