### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by cxz0101** [kkk55596/D-Former#3]
Can you give a test network code.
I ran this code with an error：TypeError: forward() takes 2 positional arguments but 5 were given 
   File "D-Former-main/D-Former-main/model.py", line 398, in forward
    x = self.pos_block(x, D, H, W)

**Comment by kkk55596** [comment]
I fix this bug. Thank you for the report.

**Comment by AbdelrahmanShakerYousef** [comment]
Hello @0925yun 

Could you please let me know how you run the code?
In which codebase? I mean the training recipes you use are based on which codebase?
