### ISSUE TITLE
What is your network input? 

### ISSUE THREAD

**Issue by cxz0101** [kkk55596/D-Former#5]
What is your network input? If I use 3090, I can only run to (7, 1, 64，128，128) [batch_size, channel, depth, W, H]，This means that my image (512，512，256) will be reduced by four times. It seems that the details have been greatly affected. How do you deal with it?

**Comment by kkk55596** [comment]
The input shape for "Synapse" is [B, 1, 64, 128, 128].

**Comment by cxz0101** [comment]
谢谢啦
